"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import base64
import json
import os
import tempfile
from pathlib import Path
from urllib.parse import urlparse

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - optional dependency in some environments
    def load_dotenv(dotenv_path=None, *args, **kwargs):
        if not dotenv_path:
            return False

        path = Path(dotenv_path)
        if not path.exists():
            return False

        loaded = False
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip()
            if not key:
                continue
            os.environ.setdefault(key, value)
            loaded = True
        return loaded

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DOTENV_PATH = BASE_DIR / ".env"
load_dotenv(DOTENV_PATH)


def _read_dotenv_value(name: str) -> str:
    if not DOTENV_PATH.exists():
        return ""

    for raw_line in DOTENV_PATH.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        if line.startswith("export "):
            line = line.removeprefix("export ").strip()

        key, value = line.split("=", 1)
        if key.strip() != name:
            continue

        return value.strip().strip("\"'")

    return ""


def _normalize_dotenv_path(raw_value: str) -> str:
    path = Path(raw_value).expanduser()
    if not path.is_absolute():
        path = BASE_DIR / path
    return str(path)


def _prefer_existing_dotenv_google_credentials():
    dotenv_credentials = _read_dotenv_value("GOOGLE_APPLICATION_CREDENTIALS")
    if not dotenv_credentials:
        return

    current_credentials = os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "")
    dotenv_credentials_path = _normalize_dotenv_path(dotenv_credentials)
    current_credentials_exists = bool(current_credentials) and Path(current_credentials).expanduser().is_file()

    if not current_credentials_exists and Path(dotenv_credentials_path).is_file():
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = dotenv_credentials_path


def _configure_google_credentials_from_env():
    current_credentials = os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "")
    if current_credentials and Path(current_credentials).expanduser().is_file():
        return

    credentials_json = os.getenv("GOOGLE_APPLICATION_CREDENTIALS_JSON", "").strip()
    credentials_b64 = os.getenv("GOOGLE_APPLICATION_CREDENTIALS_B64", "").strip()

    if not credentials_json and credentials_b64:
        try:
            credentials_json = base64.b64decode(credentials_b64).decode("utf-8")
        except (ValueError, UnicodeDecodeError):
            credentials_json = ""

    if not credentials_json:
        return

    try:
        parsed_credentials = json.loads(credentials_json)
    except json.JSONDecodeError:
        return

    credentials_path = Path(tempfile.gettempdir()) / "lektor-google-application-credentials.json"
    credentials_path.write_text(json.dumps(parsed_credentials), encoding="utf-8")
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = str(credentials_path)


_prefer_existing_dotenv_google_credentials()
_configure_google_credentials_from_env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _split_env_list(name: str) -> list[str]:
    raw_value = os.getenv(name, "")
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def _env_bool(name: str, default: bool = False) -> bool:
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    return raw_value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, default: int = 0) -> int:
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    try:
        return int(raw_value.strip())
    except (TypeError, ValueError):
        return default


# SECURITY WARNING: keep the secret key used in production secret!
DEV_SECRET_KEY = 'django-insecure-$dc5aow8tw$jzw7z+5%7=4vkk-^dhmk4fol@o=rq64#@7j#0&t'
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", DEV_SECRET_KEY)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", True)

if not DEBUG and SECRET_KEY == DEV_SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=false.")

PUBLIC_APP_ORIGIN = os.getenv("PUBLIC_APP_ORIGIN", "").strip().rstrip("/")
_PUBLIC_APP_HOST = urlparse(PUBLIC_APP_ORIGIN).hostname if PUBLIC_APP_ORIGIN else ""
ALLOW_TUNNEL_HOSTS = _env_bool("DJANGO_ALLOW_TUNNEL_HOSTS", DEBUG)

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "testserver",
    *_split_env_list("DJANGO_ALLOWED_HOSTS"),
]

if ALLOW_TUNNEL_HOSTS:
    ALLOWED_HOSTS.extend([
        ".trycloudflare.com",
        ".ngrok-free.app",
        ".ngrok-free.dev",
        ".ngrok.app",
        ".ngrok.dev",
        ".ngrok.io",
    ])

if _PUBLIC_APP_HOST and _PUBLIC_APP_HOST not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_PUBLIC_APP_HOST)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'users',
    'academics',
    'materials',
    'rest_framework',
    'corsheaders',
    'results',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

CORS_ALLOWED_ORIGINS = [
    *(
        [
            "http://127.0.0.1:5500",
            "http://localhost:5500",
        ]
        if DEBUG
        else []
    ),
    *[origin.rstrip("/") for origin in _split_env_list("CORS_ALLOWED_ORIGINS")],
]

CSRF_TRUSTED_ORIGINS = [
    *(
        [
            "http://127.0.0.1:5500",
            "http://localhost:5500",
        ]
        if DEBUG
        else []
    ),
    *[origin.rstrip("/") for origin in _split_env_list("CSRF_TRUSTED_ORIGINS")],
]

if PUBLIC_APP_ORIGIN and PUBLIC_APP_ORIGIN not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(PUBLIC_APP_ORIGIN)

if PUBLIC_APP_ORIGIN and PUBLIC_APP_ORIGIN not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(PUBLIC_APP_ORIGIN)

CORS_ALLOW_CREDENTIALS = True

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = _env_int("DJANGO_SECURE_HSTS_SECONDS", 31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    not DEBUG and SECURE_HSTS_SECONDS > 0,
)
SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GOOGLE_CLOUD_PROJECT = os.getenv("GOOGLE_CLOUD_PROJECT", "").strip()
GOOGLE_CLOUD_LOCATION = os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1").strip()
GOOGLE_GENAI_USE_VERTEXAI = _env_bool("GOOGLE_GENAI_USE_VERTEXAI", False)
GOOGLE_GENAI_MODEL_NAME = (
    os.getenv("GOOGLE_GENAI_MODEL_NAME")
    or os.getenv("VERTEX_AI_MODEL_NAME")
    or os.getenv("GEMINI_MODEL_NAME")
    or "gemini-2.5-flash"
).strip()
GOOGLE_GENAI_FALLBACK_MODELS = (
    _split_env_list("GOOGLE_GENAI_FALLBACK_MODELS")
    or _split_env_list("VERTEX_AI_FALLBACK_MODELS")
    or _split_env_list("GEMINI_FALLBACK_MODELS")
)
AZURE_SPEECH_KEY = os.getenv("AZURE_SPEECH_KEY", "").strip()
AZURE_SPEECH_REGION = os.getenv("AZURE_SPEECH_REGION", "").strip()
AZURE_SPEECH_TTS_VOICE_KK = os.getenv("AZURE_SPEECH_TTS_VOICE_KK", "kk-KZ-AigulNeural").strip()
AZURE_SPEECH_TTS_VOICE_RU = os.getenv("AZURE_SPEECH_TTS_VOICE_RU", "ru-RU-SvetlanaNeural").strip()
AZURE_SPEECH_TTS_VOICE_EN = os.getenv("AZURE_SPEECH_TTS_VOICE_EN", "en-US-JennyNeural").strip()
AZURE_SPEECH_TTS_OUTPUT_FORMAT = os.getenv(
    "AZURE_SPEECH_TTS_OUTPUT_FORMAT",
    "audio-24khz-48kbitrate-mono-mp3",
).strip()
AZURE_SPEECH_STT_API_VERSION = os.getenv("AZURE_SPEECH_STT_API_VERSION", "2025-10-15").strip()
AZURE_SPEECH_STT_LOCALES = _split_env_list("AZURE_SPEECH_STT_LOCALES") or ["kk-KZ"]
AZURE_SPEECH_STT_TIMEOUT_SECONDS = _env_int("AZURE_SPEECH_STT_TIMEOUT_SECONDS", 60)
VOICE_ASSISTANT_NAME = os.getenv("VOICE_ASSISTANT_NAME", "Ayla").strip() or "Ayla"
MAX_MATERIAL_UPLOAD_BYTES = _env_int("MAX_MATERIAL_UPLOAD_BYTES", 50 * 1024 * 1024)
