# Generated by Django 6.0.3 on 2026-03-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='language',
            field=models.CharField(default='kaz', max_length=10),
        ),
    ]
