# Generated by Django 6.0.3 on 2026-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_discipline_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='language',
            field=models.CharField(choices=[('kaz', 'Kazakh'), ('rus', 'Russian')], default='kaz', max_length=10),
        ),
    ]
