# Generated by Codex on 2026-04-08

from django.db import migrations, models


def backfill_discipline_owner_email(apps, schema_editor):
    Discipline = apps.get_model("academics", "Discipline")
    Material = apps.get_model("materials", "Material")

    system_owner_emails = {
        email.strip().lower()
        for email in Material.objects.exclude(owner_email="").values_list("owner_email", flat=True)
        if str(email or "").strip()
    }
    fallback_owner_email = next(iter(system_owner_emails)) if len(system_owner_emails) == 1 else ""

    for discipline in Discipline.objects.all():
        related_owner_emails = {
            email.strip().lower()
            for email in Material.objects.filter(discipline_id=discipline.id).exclude(owner_email="").values_list("owner_email", flat=True)
            if str(email or "").strip()
        }

        owner_email = ""
        if len(related_owner_emails) == 1:
            owner_email = next(iter(related_owner_emails))
        elif not related_owner_emails and fallback_owner_email:
            owner_email = fallback_owner_email

        if owner_email and discipline.owner_email != owner_email:
            discipline.owner_email = owner_email
            discipline.save(update_fields=["owner_email"])


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_discipline_language"),
        ("materials", "0003_material_drive_file_id_material_drive_folder_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipline",
            name="owner_email",
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.RunPython(backfill_discipline_owner_email, migrations.RunPython.noop),
    ]
