# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_discipline_owner_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discipline",
            name="language",
            field=models.CharField(
                choices=[("kaz", "Kazakh"), ("rus", "Russian"), ("eng", "English")],
                default="kaz",
                max_length=10,
            ),
        ),
    ]
