# Generated by Django 6.0.3 on 2026-03-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('lecture', 'Дәріс'), ('practice', 'Практикалық жұмыс'), ('lab', 'Зертханалық жұмыс'), ('sowj', 'СОӨЖ'), ('syllabus', 'Силлабус')], max_length=20)),
                ('cloud_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.discipline')),
            ],
        ),
    ]
