# Generated by Django 6.0.3 on 2026-04-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_form_url_material_results_sheet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
