# Generated by Django 6.0.3 on 2026-04-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_material_drive_file_id_material_drive_folder_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="slides_download_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="material",
            name="slides_embed_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="material",
            name="slides_presentation_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="material",
            name="slides_url",
            field=models.URLField(blank=True),
        ),
    ]
