# Generated by Django 6.0.3 on 2026-04-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(max_length=254, unique=True)),
                ('google_name', models.CharField(blank=True, max_length=255)),
                ('credentials_json', models.JSONField(blank=True, default=dict)),
                ('root_folder_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
